### ISSUE TITLE
Incorrect links

### ISSUE THREAD

**Issue by mpetuska** [zeplin/cli-connect-storybook-plugin#23]
The plugin generates incorrect links. 
Actual: `http://host.com/?path=/docs/input-dropdown--default`
Expected: `http://host.com/?path=/story/input-dropdown--default`

"@storybook/react@5.3.18"

**Comment by yuqu** [comment]
Do you use DocsPage on your Storybook? `/docs/` hyperlinks are created if the story has a correspondent DocsPage.

I wanted to add a configuration flag to enforce `/story/` hyperlinks even if DocsPage exists, I can prioritize it if that would work for you.

**Comment by mpetuska** [comment]
No, /docs just redirects to /story. Enforcing this would solve my issues, so having this sooner would be much appreciated.

**Comment by jonoroboto** [comment]
Having the same issue here, never had docs within our Storybook config, but the plugin seems to be linking to Docs. Exact same as above
---
Actual: http://host.com/?path=/docs/input-dropdown--default
Expected: http://host.com/?path=/story/input-dropdown--default

**Comment by yuqu** [comment]
Sorry for my late response. 

v0.3.0 is published. I've decided to keep `/story/` as default since there will always be a story page regardless of addons. User can opt-in for `/docs/` with [`useDocsPage` boolean parameter](https://github.com/zeplin/cli-connect-storybook-plugin#generate-docspage-hyperlinks).
